version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      # I don't remember, why wro4j 1.8 shall be ignored, but at least wro4j 1.9 requires Java 9.
      - dependency-name: ro.isdc.wro4j:wro4j-core
        versions:
          - "> 1.8"
      - dependency-name: ro.isdc.wro4j:wro4j-extensions
        versions:
          - "> 1.8"
      # Switch to the new jakarta.* packages
      - dependency-name: org.hibernate.validator.hibernate-validator
        versions:
          - ">= 7"
      - dependency-name: org.hibernate.validator.hibernate-validator-annotation-processor
        versions:
          - ">= 7"
      # Versions 2.0.0 and 2.0.2 are older than version 1.3 and later
      - dependency-name: xml-apis:xml-apis
        versions:
          - ">= 2.0.0"
          - ">= 2.0.2"
  - package-ecosystem: npm
    directory: /ui/src/main/angular2
    schedule:
      interval: monthly
