language: java
jdk:
  - openjdk8
  - openjdk11
env:
  - NODE_VERSION="12.16.1"

before_install: nvm install $NODE_VERSION
install: skip
script: mvn install -Dgpg.skip=true --batch-mode --show-version --update-snapshots

cache:
  directories:
    - $HOME/.m2/repository