language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2/repository

install: |
  set -o errexit -o pipefail
  mvn clean install --activate-profiles dirty,dirty-package --update-snapshots --batch-mode --show-version 2>&1 | tee mvnout.txt
script: |
  set -o errexit -o pipefail
  mvn verify site --define gpg.skip=true --define skip.installnodenpm=true --define skip.npm=true --batch-mode --show-version 2>&1 | tee --append mvnout.txt
  set +o errexit +o pipefail
  
  echo ""
  echo "[INFO] Checking for Maven warnings and errors..."
  chmod +x ./target/travis-suppressions-parent.sh
  mvnout=`cat mvnout.txt | grep --perl-regexp "(?i)\\[(ERR|WARN)" | ./target/travis-suppressions-parent.sh`
  
  if [ -n "${mvnout}" ]; then
    echo "[WARNING] The Maven output contains the following unknown warnings and errors:"
    echo "${mvnout}"
    # Not using "exit 1" to avoid truncated output as described at https://travis-ci.community/t/7159
    false
  else
    echo "[INFO] No unknown warnings and errors found."
    echo "${mvnout}"
  fi

after_success:
  - rm ./target/site/index.html
  - cp ./CHANGELOG.md ./target/site/CHANGELOG.md
  - cp ./README.md ./target/site/README.md
  
  # Modules
  - cp -R ./core/target/site ./target/site/core
  - cp -R ./jira-rest-java-client-fix/target/site ./target/site/jira-rest-java-client-fix
  - cp -R ./ui/target/site ./target/site/ui
deploy:
  provider: pages
  local_dir: ./target/site
  edge: true
  on:
    branch: develop
    jdk: openjdk8