language: java
jdk:
  - openjdk8
  - openjdk11
node_js:
  - 12

install: skip
script: mvn install -Dgpg.skip=true --batch-mode --show-version --update-snapshots

cache:
  directories:
    - $HOME/.m2/repository