language: java
install: mvn install -DskipTests=true -Dgpg.skip=true --batch-mode --show-version

env:
  - NODE_VERSION="8.12.0"

before_install:
  - nvm install $NODE_VERSION
  - npm install -g @angular/cli