POST http://localhost/events
Content-Type: application/json
Authorization: Basic user1 password
x-Oversigt-API-key: 7bcc2fd0-31f1-4c35-be8c-fe0b2b484053

{
  "id": "InternetTextExtractionEventSource__29564046_93de_4e59_aa14_84f0e6ced05d",
  "updatedAt": 1563829463,
  "moreinfo": null,
  "title": "abc",
  "items": [
    {
      "label": "delectus aut autem2",
      "value": "",
      "labelStyle": "",
      "valueStyle": ""
    }
  ]
}
