/**
 * Oversigt API
 * This API provides access to all public operations of Oversigt.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Dashboard {
    /**
     * The unique ID of the dashboard. It will be used to reference the dashboard.
     */
    id: string;
    /**
     * The title of the dashboard for display in the browser
     */
    title: string;
    /**
     * Whether the dashboard is available to the public
     */
    enabled: boolean;
    /**
     * The screen width the dashboard will be optimized for
     */
    screenWidth: number;
    /**
     * The screen height the dashboard will be optimized for
     */
    screenHeight: number;
    /**
     * The number of columns the dashboard will show if displayed without zoom
     */
    columns: number;
    /**
     * The background color of the dashboard
     */
    backgroundColor: string;
    /**
     * The type of coloring the dashboard will use
     */
    colorScheme: Dashboard.ColorSchemeEnum;
    /**
     * The first color for the selected color scheme
     */
    foregroundColorStart: string;
    /**
     * The second color for the selected color scheme
     */
    foregroundColorEnd: string;
    /**
     * The user id of dashboard's owner
     */
    owners: Array<string>;
    /**
     * A list of user ids of people who are allowed to edit the dashboard
     */
    editors: Array<string>;
}
export namespace Dashboard {
    export type ColorSchemeEnum = 'COLORED' | 'SINGLE_COLOR' | 'TILED_VERTICAL_GRADIENT' | 'TILED_HORIZONTAL_GRADIENT' | 'VERTICAL_GRADIENT' | 'HORIZONTAL_GRADIENT';
    export const ColorSchemeEnum = {
        COLORED: 'COLORED' as ColorSchemeEnum,
        SINGLECOLOR: 'SINGLE_COLOR' as ColorSchemeEnum,
        TILEDVERTICALGRADIENT: 'TILED_VERTICAL_GRADIENT' as ColorSchemeEnum,
        TILEDHORIZONTALGRADIENT: 'TILED_HORIZONTAL_GRADIENT' as ColorSchemeEnum,
        VERTICALGRADIENT: 'VERTICAL_GRADIENT' as ColorSchemeEnum,
        HORIZONTALGRADIENT: 'HORIZONTAL_GRADIENT' as ColorSchemeEnum
    }
}
