/**
 * Oversigt API
 * This API provides access to all public operations of Oversigt.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EventSourceKey } from './eventSourceKey';
import { EventSourceProperty } from './eventSourceProperty';


export interface EventSourceDescriptor { 
    key: EventSourceKey;
    displayName: string;
    description?: string;
    properties: Array<EventSourceProperty>;
    dataItems: Array<EventSourceProperty>;
    readonly view?: string;
    readonly eventClassName?: string;
    readonly serviceClassName?: string;
}
