/**
 * Oversigt API
 * This API provides access to all public operations of Oversigt.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RunStatistic } from './runStatistic';


export interface EventSourceInstanceState {
    id?: string;
    serviceClass?: string;
    createdBy?: string;
    lastChangedBy?: string;
    running?: boolean;
    automaticallyStarted?: boolean;
    statistics?: Array<RunStatistic>;
    lastSuccessfulRun?: RunStatistic;
    lastRun?: RunStatistic;
}
