/**
 * Oversigt API
 * This API provides access to all public operations of Oversigt.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SerializablePropertyMember { 
    name?: string;
    displayName?: string;
    type?: SerializablePropertyMember.TypeEnum;
    icon?: string;
    size?: number;
    required?: boolean;
}
export namespace SerializablePropertyMember {
    export type TypeEnum = 'text' | 'number' | 'password' | 'color';
    export const TypeEnum = {
        Text: 'text' as TypeEnum,
        Number: 'number' as TypeEnum,
        Password: 'password' as TypeEnum,
        Color: 'color' as TypeEnum
    };
}
