/**
 * Oversigt API
 * This API provides access to all public operations of Oversigt.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ServiceInfo { 
    readonly createdBy?: string;
    readonly lastChangeBy?: string;
    readonly running?: boolean;
    readonly lastFailureDateTime?: Date;
    readonly lastFailureDescription?: string;
    readonly lastFailureException?: string;
    readonly lastRun?: Date;
    readonly lastSuccessfulRun?: Date;
}
