/**
 * Oversigt API
 * This API provides access to all public operations of Oversigt.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StackTraceElement } from './stackTraceElement';


export interface ThreadInfo { 
    name?: string;
    id?: number;
    priority?: number;
    state?: ThreadInfo.StateEnum;
    stackTrace?: Array<StackTraceElement>;
}
export namespace ThreadInfo {
    export type StateEnum = 'NEW' | 'RUNNABLE' | 'BLOCKED' | 'WAITING' | 'TIMED_WAITING' | 'TERMINATED';
    export const StateEnum = {
        NEW: 'NEW' as StateEnum,
        RUNNABLE: 'RUNNABLE' as StateEnum,
        BLOCKED: 'BLOCKED' as StateEnum,
        WAITING: 'WAITING' as StateEnum,
        TIMEDWAITING: 'TIMED_WAITING' as StateEnum,
        TERMINATED: 'TERMINATED' as StateEnum
    };
}
