name: Build Docker Image
on:
  - workflow_dispatch

jobs:
  build-project:
    runs-on: ubuntu-latest
    name: Build with JDK 8
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v2.1.5
        with:
          key: maven-dependencies
          path: ~/.m2/repository
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Clean, Package
        run: mvn clean package --update-snapshots --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: runnable-zip
          path: |
            core/target/*.zip
            Dockerfile
  
  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: runnable-zip
      - name: Unzip artifact
        run: unzip *.zip
      - name: Delete ZIP files
        run: unzip *.zip
      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
      