name: Build on Push and Pull Request
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 1.8

    name: Build with JDK ${{ matrix.java-version }}
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          key: maven-dependencies
          path: ~/.m2/repository
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Clean, Build, Install
        run: |
          set -o errexit -o pipefail
          cd artifactory-staging-maven-plugin
          mvn clean install --update-snapshots --batch-mode --show-version 2>&1 | tee mvnout.txt
          cd ../jira-rest-java-client-parent
          mvn clean install --update-snapshots --batch-mode --show-version 2>&1 | tee --append mvnout.txt
          cd ..
          mvn clean install --activate-profiles dirty,dirty-package --update-snapshots --define skip.installnodenpm=true --define skip.npm=true --batch-mode --show-version 2>&1 | tee --append mvnout.txt
          set +o errexit +o pipefail
      - name: Test, Verify
        if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/develop' || matrix.java-version != '1.8' }}
        run: |
          set -o errexit -o pipefail
          mvn verify site --define gpg.skip=true --define skip.installnodenpm=true --define skip.npm=true --batch-mode --show-version 2>&1 | tee --append mvnout.txt
          set +o errexit +o pipefail
      - name: Check Output
        run: |
          chmod +x ./target/travis-suppressions-parent.sh
          mvnout=`cat mvnout.txt | grep --perl-regexp "(?i)\\[(ERR|WARN)" | ./target/travis-suppressions-parent.sh "$JDK_VERSION"`
          
          if [ -n "${mvnout}" ]; then
            echo "[ERROR] The Maven output contains the following unknown warnings and errors:" >&2
            echo "${mvnout}"
            false
          else
            echo "[INFO] No unknown warnings and errors found."
            echo "${mvnout}"
          fi
        env:
          JDK_VERSION: ${{ matrix.java-version }}
      - name: Prepare Site
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' && matrix.java-version == '1.8' }}
        run: |
          rm ./target/site/index.html
          cp ./CHANGELOG.md ./target/site/CHANGELOG.md
          cp ./README.md ./target/site/README.md
          
          # Modules
          cp -R ./core/target/site ./target/site/core
          cp -R ./jira-rest-java-client-fix/target/site ./target/site/jira-rest-java-client-fix
          cp -R ./ui/target/site ./target/site/ui
