name: Build on Push and Pull Request
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8

    name: Build with JDK ${{ matrix.java-version }}
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v2.1.4
        with:
          key: maven-dependencies
          path: ~/.m2/repository
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}
      - name: Clean, Build, Install
        run: |
          set -o errexit -o pipefail
          mvn clean install --activate-profiles dirty,dirty-package --update-snapshots --define skip.installnodenpm=true --define skip.npm=true --batch-mode --show-version 2>&1 | tee --append mvnout.txt
          set +o errexit +o pipefail
      - name: Test, Verify
        if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/develop' || matrix.java-version != '8' }}
        run: |
          set -o errexit -o pipefail
          mvn verify --define gpg.skip=true --define skip.installnodenpm=true --define skip.npm=true --batch-mode --show-version 2>&1 | tee --append mvnout.txt
          set +o errexit +o pipefail
      - name: Check Output
        shell: bash {0}
        run: |
          chmod +x ./target/travis-suppressions-parent.sh
          mvnout=`cat mvnout.txt | grep --perl-regexp "(?i)\\[(ERR|WARN)" | ./target/travis-suppressions-parent.sh "$JDK_VERSION"`
          
          if [ -n "${mvnout}" ]; then
            echo "[ERROR] The Maven output contains the following unknown warnings and errors:" >&2
            echo "${mvnout}" >&2
            false
          else
            echo "[INFO] No unknown warnings and errors found."
            echo "${mvnout}" >&2
          fi
        env:
          JDK_VERSION: ${{ matrix.java-version }}
